### ISSUE TITLE
Links in Properties view are not clickable

### ISSUE THREAD

**Issue by paulvi** [mikekelly/hal-browser#82]
It would be nice to have Links in Properties view to be clickable

``` html
<div class="resource"><div class="properties">
    <h2>Properties</h2>
    <pre>{
  "links": [
    {
      "rel": "customer",
      "href": "http://localhost:8080/rest/customer{?page,size,sort}"
    },
    {
      "rel": "profile",
      "href": "http://localhost:8080/rest/profile"
    }
  ]
}</pre>
</div><div class="links">
    <h2>Links</h2>
    <table class="table">
        <thead>
        <tr>
            <th>rel</th>
            <th>title</th>
            <th>name / index</th>
            <th>docs</th>
            <th>GET</th>
            <th>NON-GET</th>
        </tr>
        </thead>
        <tbody>

        </tbody>
    </table>
</div></div>
```

**Comment by upachler** [comment]
Yeah, that feature is dearly missed!

++1

**Comment by upachler** [comment]
Hi, I implemented that.. :)

**Comment by upachler** [comment]
Now that my change is merged, could this issue be closed now? 
Also, it'd be nice to make a new webjars release of hal-browser that has that change - how can we do that?

**Comment by mikekelly** [comment]
no idea about webjars, sorry

**Comment by leanjaxrs** [comment]
already done :)

-> On the webjars.org page, you can simply request a new version, and the folks there pull it from your git repo and get it deployed to Maven central (hal-browser is a 'classic webjar' as they call it).
